on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: master
jobs:
  build:
    name: Build on Linux
    container: ubuntu:noble
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get -y install -y autoconf build-essential check git pkg-config

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: 'recursive'

    - name: Configure
      run: |
        ./autogen.sh
        ./configure

    - name: Build
      run: |
        make
        make check
