on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: master
jobs:
  build:
    name: Build on Linux
    container: ubuntu:noble
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        set -e
        apt-get update -y
        apt-get install -y git autoconf gcc pkg-config check

    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Configure
      run: |
        set -e
        ./autogen.sh
        ./configure

    - name: Build
      run: |
        set -e
        make
        make install
        make check
